Repository MicrosoftDocs/azure-docs.pl-pl, pull requests merged in 2019-08, with the labels that each got.

#346 Fix mistranslation
  articles/data-factory/connector-azure-sql-data-warehouse.md
Labels: Accepted

#349 Fix mistranslation
  articles/data-factory/connector-file-system.md
Labels: Accepted

#350 Fix mistranslation
  articles/data-factory/connector-google-cloud-storage.md
Labels: Accepted

#351 Fix mistranslation
  articles/data-factory/connector-hdfs.md
Labels: Accepted

#353 Fix mistranslation
  articles/data-factory/connector-http.md
Labels: Accepted

#352 Fix mistranslation
  articles/data-factory/connector-hive.md
Labels: Accepted

#354 Fix mistranslation
  articles/data-factory/connector-mongodb-legacy.md
Labels: Accepted

#356 Fix mistranslation
  articles/data-factory/connector-odata.md
Labels: Accepted

#355 Fix mistranslation
  articles/data-factory/connector-mongodb.md
Labels: Accepted

#357 Fix mistranslation
  articles/data-factory/connector-oracle.md
Labels: Accepted

#358 Fix mistranslation
  articles/data-factory/connector-rest.md
Labels: Accepted

#359 Fix mistranslation
  articles/data-factory/connector-salesforce.md
Labels: Accepted

#360 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse-open-hub.md
Labels: Accepted

#361 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse.md
Labels: Accepted

#362 Fix mistranslation
  articles/data-factory/connector-sap-cloud-for-customer.md
Labels: Accepted

#363 Fix mistranslation
  articles/data-factory/connector-sap-hana.md
Labels: Accepted

#364 Fix mistranslation
  articles/data-factory/connector-sftp.md
Labels: Accepted

#365 Fix mistranslation
  articles/data-factory/connector-shopify.md
Labels: Accepted

#367 Fix mistranslation
  articles/data-factory/connector-sql-server.md
Labels: Accepted

#366 Fix mistranslation
  articles/data-factory/connector-spark.md
Labels: Accepted

#368 Fix mistranslation
  articles/data-factory/connector-square.md
Labels: Accepted

#369 Fix mistranslation
  articles/data-factory/connector-sybase.md
Labels: Accepted

#370 Fix mistranslation
  articles/data-factory/connector-teradata.md
Labels: Accepted

#371 Fix mistranslation
  articles/data-factory/connector-vertica.md
Labels: Accepted

#372 Fix mistranslation
  articles/data-factory/connector-web-table.md
Labels: Accepted

#373 Fix mistranslation
  articles/data-factory/connector-xero.md
Labels: Accepted

#374 Fix mistranslation
  articles/data-factory/connector-zoho.md
Labels: Accepted, Linguistic Suggestion

#375 Fix mistranslation
  articles/data-factory/copy-activity-overview.md
Labels: Accepted, Linguistic Suggestion

#376 Fix mistranslation
  articles/data-factory/copy-activity-schema-and-type-mapping.md
Labels: Accepted, Linguistic Suggestion

#379 Fix mistranslation
  articles/data-factory/monitor-integration-runtime.md
Labels: Accepted

#378 Fix mistranslation
  articles/data-factory/how-to-create-tumbling-window-trigger.md
Labels: Accepted

#380 Fix mistranslation
  articles/data-factory/monitor-using-azure-monitor.md
Labels: Accepted

#381 Fix mistranslation
  articles/data-factory/v1/data-factory-amazon-simple-storage-service-connector.md
Labels: Accepted, Linguistic Suggestion

#312 Update howto-mfa-reporting.md
  articles/active-directory/authentication/howto-mfa-reporting.md
Labels: Accepted, Source Issue

#382 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-blob-connector.md
Labels: Accepted

#383 Fix mistranslation
  articles/data-factory/connector-dynamics-crm-office-365.md
Labels: Accepted

#399 Fix mistranslation
  articles/data-factory/connector-oracle-eloqua.md
Labels: Accepted

#398 Fix mistranslation
  articles/data-factory/connector-microsoft-access.md
Labels: Accepted

#397 Fix mistranslation
  articles/data-factory/connector-jira.md
Labels: Accepted

#396 Fix mistranslation
  articles/data-factory/connector-informix.md
Labels: Accepted

#395 Fix mistranslation
  articles/data-factory/connector-hdfs.md
Labels: Accepted

#394 Fix mistranslation
  articles/data-factory/connector-google-cloud-storage.md
Labels: Accepted

#393 Fix mistranslation
  articles/data-factory/connector-concur.md
Labels: Accepted

#392 Fix mistranslation
  articles/data-factory/connector-azure-sql-database-managed-instance.md
Labels: Accepted

#391 Fix mistranslation
  articles/data-factory/connector-azure-file-storage.md
Labels: Accepted

#390 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-store.md
Labels: Accepted

#389 Fix mistranslation
  articles/data-factory/connector-azure-data-explorer.md
Labels: Accepted

#388 Fix mistranslation
  articles/data-factory/connector-azure-cosmos-db-mongodb-api.md
Labels: Accepted

#387 Fix mistranslation
  articles/data-factory/connector-amazon-simple-storage-service.md
Labels: Accepted

#386 Fix mistranslation
  articles/data-factory/connector-amazon-marketplace-web-service.md
Labels: Accepted

#385 Fix mistranslation
  articles/data-factory/compute-linked-services.md
Labels: Accepted

#384 Fix mistranslation
  articles/blockchain/workbench/messages-overview.md
Labels: Accepted

#407 Fix mistranslation
  articles/data-factory/format-binary.md
Labels: Accepted

#406 Fix mistranslation
  articles/data-factory/control-flow-azure-function-activity.md
Labels: Accepted

#405 Fix mistranslation
  articles/data-factory/connector-servicenow.md
Labels: Accepted

#404 Fix mistranslation
  articles/data-factory/connector-salesforce-service-cloud.md
Labels: Accepted

#403 Fix mistranslation
  articles/data-factory/connector-salesforce-marketing-cloud.md
Labels: Accepted

#402 Fix mistranslation
  articles/data-factory/connector-quickbooks.md
Labels: Accepted

#401 Fix mistranslation
  articles/data-factory/connector-oracle-service-cloud.md
Labels: Accepted

#400 Fix mistranslation
  articles/data-factory/connector-oracle-responsys.md
Labels: Accepted

#425 Fix mistranslation
  articles/virtual-machines/extensions/hpccompute-gpu-windows.md
Labels: Accepted

#424 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-windows.md
Labels: Accepted

#423 Fix mistranslation
  articles/virtual-machines/extensions/chef.md
Labels: Accepted

#422 Fix mistranslation
  articles/data-factory/v1/data-factory-web-table-connector.md
Labels: Accepted

#421 Fix mistranslation
  articles/data-factory/v1/data-factory-usql-activity.md
Labels: Accepted

#420 Fix mistranslation
  articles/data-factory/v1/data-factory-salesforce-connector.md
Labels: Accepted

#419 Fix mistranslation
  articles/data-factory/v1/data-factory-json-scripting-reference.md
Labels: Accepted

#418 Fix mistranslation
  articles/data-factory/v1/data-factory-create-pipelines.md
Labels: Accepted

#417 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-rest-api.md
Labels: Accepted

#416 Fix mistranslation
  articles/data-factory/v1/data-factory-compute-linked-services.md
Labels: Accepted

#415 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-powershell.md
Labels: Accepted

#414 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-data-warehouse-connector.md
Labels: Accepted

#413 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-connector.md
Labels: Accepted

#412 Fix mistranslation
  articles/data-factory/tumbling-window-trigger-dependency.md
Labels: Accepted

#411 Fix mistranslation
  articles/data-factory/transform-data-using-hadoop-hive.md
Labels: Accepted

#410 Fix mistranslation
  articles/data-factory/transform-data-using-data-lake-analytics.md
Labels: Accepted

#409 Fix mistranslation
  articles/data-factory/format-parquet.md
Labels: Accepted

#408 Fix mistranslation
  articles/data-factory/format-delimited-text.md
Labels: Accepted
